# Generated by Django 5.0.6 on 2024-05-11 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(null=True)),
                ('description', models.TextField(null=True)),
                ('status', models.IntegerField(choices=[(1, 'active'), (0, 'inactive')], default=1)),
                ('created_date', models.DateTimeField()),
                ('modified_date', models.DateTimeField()),
            ],
        ),
    ]
