# Generated by Django 5.0.6 on 2024-05-11 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_app', '0002_alter_services_created_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='status',
            field=models.BooleanField(choices=[(1, 'active'), (0, 'inactive')], default=1),
        ),
    ]
